version: '3.0'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: apache/kafka
    container_name: kafka
    ports:
      - "9091:9091"
    environment:
      KAFKA_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181