server:
  port: 9192

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: learn-kafka-grp-1
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer